import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";
import SideMenu from "./_components/Sidebar";
import MobileMenu from "./_components/Sidebar/Mobile.Component";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Soumitra Saha",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <main className="grid grid-cols-12 gap-4">
            {/* Mobile Menu */}
            <main className="col-span-full md:hidden">
              <MobileMenu />
            </main>

            {/* Desktop Menu */}
            <main className="hidden md:col-span-3 md:block xl:col-span-2">
              <SideMenu />
            </main>

            {/* Body */}
            <main className="col-span-full md:col-span-9 xl:col-span-10">
              {children}
            </main>
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
